<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.system.announcement</groupId>
        <artifactId>systemannouncement-parent</artifactId>
        <version>25.104.2-M1-SNAPSHOT</version>
    </parent>

    <artifactId>systemannouncement-api</artifactId>
    <packaging>war</packaging>

    <properties>
        <cpp.service-component>SystemAnnouncement.API</cpp.service-component>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>

    <dependencies>
        <dependency>
            <groupId>uk.gov.moj.cpp.system.announcement</groupId>
            <artifactId>systemannouncement-persistence-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.system.announcement</groupId>
            <artifactId>systemannouncement-domain-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>command-api</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Apache commons -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-reload4j</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-event-source</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-enveloper-provider</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-servlet-initializer</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-generators</groupId>
            <artifactId>rest-adapter-file-service</artifactId>
            <version>17.100.4</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.access-control</groupId>
            <artifactId>access-control-test-utils</artifactId>
            <version>17.21.17</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>jakarta.platform</groupId>
                        <artifactId>jakarta.jakartaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>